$(function(){
    $('.btn2').hover(function(){
        //mouseover
        $('.txt2').css('background','aqua');
    },function(){
        //mouseout
        $('.txt2').css('background','none');
    });
});